const BASE_URL = "https://etjyvuvqxyn1sjp-g0gyvjofm9d4w4k4.adb.us-ashburn-1.oraclecloudapps.com/ords/admin"; // 改成你的实际地址
const ADMIN_SCHEMA = "admin";

async function tableExists(tableName: string): Promise<boolean> {
    const resp = await fetch(`${BASE_URL}/metadata-catalog/${ADMIN_SCHEMA}/tables/${tableName}`, { method: 'GET' });
    return resp.ok;
}

async function createTable(tableName: string): Promise<void> {
    const sql = `
    CREATE TABLE ${ADMIN_SCHEMA}.${tableName} (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      color VARCHAR2(50),
      event_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      trace_id VARCHAR2(100),
      source CHAR(1),
      extra CLOB
    )
  `;
    await fetch(`${BASE_URL}/sql`, {
        method: 'POST',
        headers: { "Content-Type": "application/sql" },
        body: sql
    });
}

async function registerRestApi(tableName: string): Promise<void> {
    const payload = {
        module_name: "default",
        base_path: "/",
        privileges: "unauthenticated",
        objects: [
            {
                object_name: tableName,
                object_alias: tableName,
                http_methods_allowed: "GET,POST"
            }
        ]
    };
    await fetch(`${BASE_URL}/metadata-catalog/${ADMIN_SCHEMA}/modules/default`, {
        method: 'PUT',
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
    });
}

export async function ensureMonthlyTableAndRestApi(tableName: string): Promise<void> {
    if (await tableExists(tableName)) return;
    await createTable(tableName);
    await registerRestApi(tableName);
}

export async function insertColorRecord(tableName: string, color: string, traceId: string, source: string): Promise<void> {
    const url = `${BASE_URL}/${tableName}/`;
    await fetch(url, {
        method: 'POST',
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            color,
            trace_id: traceId,
            source,
            extra: null
        })
    });
}
