begin
   execute immediate 'DROP TABLE color_events PURGE';
exception
   when others then
      if sqlcode = -942 then
         null;
      else
         raise;
      end if;
end;

create table color_events (
   id               number
      generated by default as identity
   primary key,
   color            varchar2(7),
   event_at         timestamp default current_timestamp,
   trace_id         varchar2(36),
   source           char(1)
      constraint check_color_events_src check ( source in ( 'a',
                                                            'c',
                                                            'i',
                                                            's' ) ),
   client_ip        varchar2(45) null,
   user_agent       varchar2(1000) null,
   referer          varchar2(2000) null,
   cf_country       varchar2(2) null,
   cf_colo          varchar2(10) null,
   cf_asn           number null,
   cf_http_protocol varchar2(10) null,
   cf_tls_cipher    varchar2(100) null,
   cf_tls_version   varchar2(10) null,
   cf_threat_score  number null,
   cf_trust_score   number null,
   extra            clob
)
   partition by range (
      event_at
   ) interval ( numtoyminterval(
      1,
      'MONTH'
   ) ) ( partition p_initial
      values less than ( timestamp '2024-01-01 00:00:00' )
   );

begin
   execute immediate 'DROP INDEX ix_color_events_eventat';
exception
   when others then
      if sqlcode = -1418 then
         null;
      else
         raise;
      end if;
end;

begin
   execute immediate 'DROP INDEX ix_color_events_traceid';
exception
   when others then
      if sqlcode = -1418 then
         null;
      else
         raise;
      end if;
end;

create index ix_color_events_eventat on
   color_events (
      event_at
   )
      local;

create index ix_color_events_traceid on
   color_events (
      trace_id
   )
      local;