-- database/tables/colors_log.sql (完整版)

-- 先尝试删除旧表（如果存在），忽略错误
BEGIN EXECUTE IMMEDIATE 'DROP TABLE colors_log PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 创建包含所有列的分区表 colors_log
CREATE TABLE colors_log (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color               VARCHAR2(7),
    event_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Partition Key
    trace_id            VARCHAR2(36),
    source              CHAR(1) CONSTRAINT check_colors_log_src CHECK (source IN ('a', 'c', 'i', 's')),
    client_ip           VARCHAR2(45)   NULL,
    -- 新增列:
    user_agent          VARCHAR2(1000) NULL,
    referer             VARCHAR2(2000) NULL,
    cf_country          VARCHAR2(2)    NULL,
    cf_colo             VARCHAR2(10)   NULL,
    cf_asn              NUMBER         NULL,
    cf_http_protocol    VARCHAR2(10)   NULL,
    cf_tls_cipher       VARCHAR2(100)  NULL,
    cf_tls_version      VARCHAR2(10)   NULL,
    cf_threat_score     NUMBER         NULL,
    cf_trust_score      NUMBER         NULL,
    -- 结束新增列
    extra               CLOB
)
PARTITION BY RANGE (event_at) -- 按 event_at 列进行范围分区
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) -- 自动按月创建新分区
(
    PARTITION p_initial VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00') -- 初始分区
);


-- 删除可能已存在的旧索引 (如果脚本需要重复执行)
BEGIN EXECUTE IMMEDIATE 'DROP INDEX ix_colors_log_eventat'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX ix_colors_log_traceid'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- 如果添加了 IP 索引等，也在此处 DROP

-- 创建索引
CREATE INDEX ix_colors_log_eventat ON colors_log (event_at) LOCAL;
/
CREATE INDEX ix_colors_log_traceid ON colors_log (trace_id) LOCAL;
/
-- (可选) 根据需要为新列创建索引，例如：
-- CREATE INDEX ix_colors_log_country ON colors_log (cf_country) LOCAL;
-- /
-- CREATE INDEX ix_colors_log_asn ON colors_log (cf_asn) LOCAL;
-- /