-- Production schema for WWR_APP.COLOR_EVENTS.
-- Safe to run repeatedly: it never drops tables, indexes, or data.
-- The application writes event_at as an ISO-8601 UTC value. The production
-- Autonomous Database and session time zones are both UTC.

declare
   l_table_exists number;
begin
   select count(*)
     into l_table_exists
     from user_tables
    where table_name = 'COLOR_EVENTS';

   if l_table_exists = 0 then
      execute immediate q'[
         create table color_events (
            id               number generated by default as identity primary key,
            color            varchar2(7),
            event_at         timestamp default current_timestamp,
            trace_id         varchar2(36),
            source           char(1)
               constraint check_color_events_src check (source in ('a', 'c', 'i', 's')),
            client_ip        varchar2(45),
            user_agent       varchar2(1000),
            referer          varchar2(2000),
            cf_country       varchar2(2),
            cf_colo          varchar2(10),
            cf_asn           number,
            cf_http_protocol varchar2(10),
            cf_tls_cipher    varchar2(100),
            cf_tls_version   varchar2(10),
            cf_threat_score  number,
            cf_trust_score   number,
            extra            clob
         )
      ]';
   end if;
end;
/

declare
   l_index_exists number;
begin
   select count(*)
     into l_index_exists
     from user_indexes
    where index_name = 'IX_COLOR_EVENTS_EVENTAT';

   if l_index_exists = 0 then
      execute immediate 'create index ix_color_events_eventat on color_events (event_at)';
   end if;

   select count(*)
     into l_index_exists
     from user_indexes
    where index_name = 'IX_COLOR_EVENTS_TRACEID';

   if l_index_exists = 0 then
      execute immediate 'create index ix_color_events_traceid on color_events (trace_id)';
   end if;
end;
/
