name: Build & Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4 # <-- 更新到 v4

      # --- 设置 pnpm ---
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # <-- 使用 pnpm/action-setup
        with:
          version: 8 # 或者您在本地使用的 pnpm 主版本 (例如 10)

      # --- 设置 Node.js ---
      - name: Setup Node.js
        uses: actions/setup-node@v4 # <-- 更新到 v4
        with:
          node-version: 22 # <-- 推荐与您本地版本保持一致
          cache: 'pnpm' # <-- 为 pnpm 配置缓存

      # --- 安装依赖 ---
      - name: Install dependencies
        run: pnpm install --frozen-lockfile # <-- 使用 --frozen-lockfile

      # --- 部署 ---
      - name: Deploy to Cloudflare Workers
        # 使用 npx 调用 wrangler
        run: npx wrangler deploy # <-- 修改调用方式
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # 注意：根据您的 wrangler 配置，可能还需要设置其他环境变量，例如您的 Workers 项目名称
          # 例如：VAR_WORKER_NAME: your-worker-name # 如果 wrangler.toml 中使用了变量

          